"""
Project Euler Problem 61
========================

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers
are all figurate (polygonal) numbers and are generated by the following
formulae:

Triangle     P[3,n]=n(n+1)/2    1, 3, 6, 10, 15, ...
Square       P[4,n]=n^2         1, 4, 9, 16, 25, ...
Pentagonal   P[5,n]=n(3n-1)/2   1, 5, 12, 22, 35, ...
Hexagonal    P[6,n]=n(2n-1)     1, 6, 15, 28, 45, ...
Heptagonal   P[7,n]=n(5n-3)/2   1, 7, 18, 34, 55, ...
Octagonal    P[8,n]=n(3n-2)     1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three
interesting properties.

 1. The set is cyclic, in that the last two digits of each number is the
    first two digits of the next number (including the last number with
    the first).
 2. Each polygonal type: triangle (P[3,127]=8128), square (P[4,91]=8281),
    and pentagonal (P[5,44]=2882), is represented by a different number in
    the set.
 3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for
which each polygonal type: triangle, square, pentagonal, hexagonal,
heptagonal, and octagonal, is represented by a different number in the
set.
"""


def quadratic(a, b, c) -> float:
    sq = (b**2 - 4 * a * c)**(1 / 2)
    denom = 2 * a
    return max((-b + sq) / denom, (-b - sq) / denom)


def tri_inv(t: float) -> float:
    """n, given a triangle number"""
    return quadratic(1 / 2, 1 / 2, - t)


def pen_inv(p: float) -> float:
    """n, given pentagonal number."""
    return quadratic(3 / 2, -1 / 2, -p)


def hex_inv(h: float) -> float:
    """n, given hexagonal number"""
    return quadratic(2, -1, -h)


def ngon_inv(x: float) -> float:
    args_map = {
        3: (1/2, 1/2, -x),
        4: (1, 0, -x),
        5: (3/2, -1/2, -x),
        6: (2, -1, -x),
        7: (5/2, -3/2, -x),
        8: (3, -2, -x)
    }
    return quadratic(*args_map[x])


def polygon(n):
    if int(n) != n:
        return False


def main():
    pass


if __name__ == '__main__':
    pass
